// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: server.ipynb

import { Hono } from "hono";
import { downloadPostToMd } from "bsky2md/bsky.ts";

const app = new Hono();

app.get("/", async (c) => {
  return c.html(`
    <html>
      <head>
        <title>Hello Hono</title>
        <style>body {font-family: Arial, sans-serif; padding: 20px; background-color: #ffffff; }</style>
      </head>
      <body><strong>
      ${await downloadPostToMd(c.req.query().url)}
      </strong></body>
    </html>  
  `);
});
Deno.serve(app.fetch);
