name: Deploy
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Deno deploy need this
      id-token: write # Deno deploy need this

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build
        run: deno task build

      # - name: Tests
      #   run: deno test --allow-all

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "bsky2md"
          entrypoint: "bsky2md/server.ts"
          root: "."